// Generated by ingest-mxl.ts. Do not edit by hand.

import allOfMeJohnLegendEasyPianoJson from "./lessons/all-of-me-john-legend-easy-piano.json" with { type: "json" };
import amazingGraceEasyPianoJson from "./lessons/amazing-grace-easy-piano.json" with { type: "json" };
import canonInDEasyJson from "./lessons/canon-in-d-easy.json" with { type: "json" };
import ezPiano02MaryHadALittleLambJson from "./lessons/ez-piano-02-mary-had-a-little-lamb.json" with { type: "json" };
import felizNavidadEasyPianoJson from "./lessons/feliz-navidad-easy-piano.json" with { type: "json" };
import furEliseEasyVerJson from "./lessons/fur-elise-easy-ver.json" with { type: "json" };
import goldenKPopDemonHuntersJson from "./lessons/golden-k-pop-demon-hunters.json" with { type: "json" };
import goldenKpopDemonHuntersSimplifiedJson from "./lessons/golden-kpop-demon-hunters-simplified.json" with { type: "json" };
import greensleevesForPianoEasyAndBeautifulJson from "./lessons/greensleeves-for-piano-easy-and-beautiful.json" with { type: "json" };
import happyBirthdayToYouPianoJson from "./lessons/happy-birthday-to-you-piano.json" with { type: "json" };
import hitTheRoadJackEasyPianoJson from "./lessons/hit-the-road-jack-easy-piano.json" with { type: "json" };
import madWorldPianoJson from "./lessons/mad-world-piano.json" with { type: "json" };
import maryHadALittleLambTwoHandsJson from "./lessons/mary-had-a-little-lamb-two-hands.json" with { type: "json" };
import maryHadALittleLambJson from "./lessons/mary-had-a-little-lamb.json" with { type: "json" };
import minecraftThemeSwedenCalmJson from "./lessons/minecraft-theme-sweden-calm.json" with { type: "json" };
import perfectEdSheeranEasyPianoJson from "./lessons/perfect-ed-sheeran-easy-piano.json" with { type: "json" };
import superMarioBrosMainThemeJson from "./lessons/super-mario-bros-main-theme.json" with { type: "json" };
import swanLakeThemeTchaikovskyJson from "./lessons/swan-lake-theme-tchaikovsky.json" with { type: "json" };
import thePinkPantherJson from "./lessons/the-pink-panther.json" with { type: "json" };
import twinkleJson from "./lessons/twinkle.json" with { type: "json" };
import waltzInAMinorchopinJson from "./lessons/waltz-in-a-minorchopin.json" with { type: "json" };

export const catalogLessonJson = [
  allOfMeJohnLegendEasyPianoJson,
  amazingGraceEasyPianoJson,
  canonInDEasyJson,
  ezPiano02MaryHadALittleLambJson,
  felizNavidadEasyPianoJson,
  furEliseEasyVerJson,
  goldenKPopDemonHuntersJson,
  goldenKpopDemonHuntersSimplifiedJson,
  greensleevesForPianoEasyAndBeautifulJson,
  happyBirthdayToYouPianoJson,
  hitTheRoadJackEasyPianoJson,
  madWorldPianoJson,
  maryHadALittleLambTwoHandsJson,
  maryHadALittleLambJson,
  minecraftThemeSwedenCalmJson,
  perfectEdSheeranEasyPianoJson,
  superMarioBrosMainThemeJson,
  swanLakeThemeTchaikovskyJson,
  thePinkPantherJson,
  twinkleJson,
  waltzInAMinorchopinJson,
] as const;
